# Generated by Django 6.0 on 2026-05-04 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio_gestion', '0002_mantencion_programada_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('persona_nombre', models.CharField(max_length=200)),
                ('persona_rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('persona_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('persona_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('persona_domicilio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['persona_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_numero', models.CharField(max_length=20)),
                ('unidad_piso', models.CharField(blank=True, max_length=20, null=True)),
                ('unidad_block', models.CharField(blank=True, max_length=20, null=True)),
                ('unidad_tipo', models.CharField(choices=[('DEPARTAMENTO', 'Departamento'), ('CASA', 'Casa'), ('OFICINA', 'Oficina'), ('LOCAL', 'Local Comercial')], default='DEPARTAMENTO', max_length=20)),
                ('unidad_rol_sii', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominio_gestion.condominio')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'ordering': ['condominio', 'unidad_block', 'unidad_piso', 'unidad_numero'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTenencia',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenencia_tipo', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ARRENDATARIO', 'Arrendatario'), ('OCUPANTE', 'Ocupante')], max_length=20)),
                ('tenencia_fecha_inicio', models.DateField()),
                ('tenencia_fecha_termino', models.DateField(blank=True, null=True)),
                ('tenencia_activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='tenencias', to='copropietarios.persona')),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='tenencias', to='copropietarios.unidad')),
            ],
            options={
                'verbose_name': 'Registro de Tenencia',
                'verbose_name_plural': 'Registros de Tenencia',
                'db_table': 'registro_tenencia',
                'ordering': ['-tenencia_fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['condominio'], name='idx_unidad_condominio'),
        ),
        migrations.AddIndex(
            model_name='registrotenencia',
            index=models.Index(fields=['unidad'], name='idx_tenencia_unidad'),
        ),
        migrations.AddIndex(
            model_name='registrotenencia',
            index=models.Index(fields=['persona'], name='idx_tenencia_persona'),
        ),
    ]
