# Generated by Django 6.0 on 2026-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copropietarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='persona_acepta_notificacion_digital',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='persona_email_notificaciones',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='persona_tipo_documento',
            field=models.CharField(choices=[('RUT', 'RUT'), ('PASAPORTE', 'Pasaporte'), ('RNI', 'RNI')], default='RUT', max_length=20),
        ),
        migrations.AddField(
            model_name='registrotenencia',
            name='tenencia_contrato_referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad_alicuota',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad_num_bodegas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad_num_estacionamientos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad_superficie_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
