# Generated by Django 6.0 on 2026-01-23 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoTipo',
            fields=[
                ('activo_tipo_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activo_tipo_nombre', models.CharField(max_length=100)),
                ('activo_tipo_descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activos',
                'db_table': 'activo_tipo',
                'ordering': ['activo_tipo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('condominio_id', models.AutoField(primary_key=True, serialize=False)),
                ('condominio_nombre', models.CharField(max_length=100)),
                ('condominio_descripcion', models.TextField(blank=True, null=True)),
                ('condominio_ubicacion', models.TextField(blank=True, null=True)),
                ('condominio_activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'db_table': 'condominio',
                'ordering': ['condominio_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('espacio_id', models.AutoField(primary_key=True, serialize=False)),
                ('espacio_nombre', models.CharField(max_length=100)),
                ('espacio_descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion_fisica', models.TextField(blank=True, null=True)),
                ('espacio_disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='condominio_gestion.condominio')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacio',
                'ordering': ['condominio', 'espacio_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('activo_id', models.AutoField(primary_key=True, serialize=False)),
                ('activo_nombre', models.CharField(max_length=200)),
                ('activo_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('activo_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo_numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activo_estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo_tipo', models.ForeignKey(blank=True, db_column='activo_tipo_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='condominio_gestion.activotipo')),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='condominio_gestion.condominio')),
                ('espacio', models.ForeignKey(blank=True, db_column='espacio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='condominio_gestion.espacio')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'activo',
                'ordering': ['condominio', 'activo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMantencion',
            fields=[
                ('historial_mantencion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mantencion_fecha', models.DateField()),
                ('mantencion_tipo', models.CharField(blank=True, choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva'), ('EMERGENCIA', 'Emergencia')], max_length=50, null=True)),
                ('mantencion_descripcion', models.TextField(blank=True, null=True)),
                ('mantencion_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('proxima_mantencion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.ForeignKey(db_column='activo_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenciones', to='condominio_gestion.activo')),
            ],
            options={
                'verbose_name': 'Historial de Mantención',
                'verbose_name_plural': 'Historial de Mantenciones',
                'db_table': 'historial_mantencion',
                'ordering': ['-mantencion_fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['condominio'], name='idx_espacio_condominio'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['condominio'], name='idx_activo_condominio'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['espacio'], name='idx_activo_espacio'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['activo_tipo'], name='idx_activo_tipo'),
        ),
        migrations.AddIndex(
            model_name='historialmantencion',
            index=models.Index(fields=['activo'], name='idx_historial_activo'),
        ),
    ]
