# Generated by Django 6.0 on 2026-02-25 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoTipo',
            fields=[
                ('activo_tipo_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activo_tipo_nombre', models.CharField(max_length=100)),
                ('activo_tipo_descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activos',
                'db_table': 'activo_tipo',
                'ordering': ['activo_tipo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('condominio_id', models.AutoField(primary_key=True, serialize=False)),
                ('condominio_nombre', models.CharField(max_length=100)),
                ('condominio_descripcion', models.TextField(blank=True, null=True)),
                ('condominio_ubicacion', models.TextField(blank=True, null=True)),
                ('condominio_activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'db_table': 'condominio',
                'ordering': ['condominio_nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantencionEstado',
            fields=[
                ('mantencion_estado_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mantencion_estado_nombre', models.CharField(max_length=100)),
                ('mantencion_estado_descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Estado de Mantención',
                'verbose_name_plural': 'Estados de Mantención',
                'db_table': 'mantencion_estado',
                'ordering': ['mantencion_estado_nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantencionProveedor',
            fields=[
                ('mantencion_proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('mantencion_proveedor_nombre', models.TextField()),
                ('mantencion_proveedor_rut', models.TextField(blank=True, null=True)),
                ('mantencion_proveedor_activo', models.BooleanField(default=True)),
                ('mantencion_proveedor_telefono', models.TextField(blank=True, null=True)),
                ('mantencion_proveedor_email', models.TextField(blank=True, null=True)),
                ('mantencion_proveedor_administrador', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Proveedor de Mantención',
                'verbose_name_plural': 'Proveedores de Mantención',
                'db_table': 'mantencion_proveedor',
                'ordering': ['mantencion_proveedor_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('espacio_id', models.AutoField(primary_key=True, serialize=False)),
                ('espacio_nombre', models.CharField(max_length=100)),
                ('espacio_descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion_fisica', models.TextField(blank=True, null=True)),
                ('espacio_disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='condominio_gestion.condominio')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacio',
                'ordering': ['condominio', 'espacio_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('activo_id', models.AutoField(primary_key=True, serialize=False)),
                ('activo_nombre', models.CharField(max_length=200)),
                ('activo_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('activo_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo_numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activo_estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo_tipo', models.ForeignKey(blank=True, db_column='activo_tipo_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='condominio_gestion.activotipo')),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='condominio_gestion.condominio')),
                ('espacio', models.ForeignKey(blank=True, db_column='espacio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='condominio_gestion.espacio')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'activo',
                'ordering': ['condominio', 'activo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('mantencion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mantencion_tipo', models.CharField(blank=True, choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva'), ('EMERGENCIA', 'Emergencia')], max_length=50, null=True)),
                ('mantencion_descripcion', models.TextField(blank=True, null=True)),
                ('mantencion_fecha_realizacion', models.DateField(blank=True, null=True)),
                ('mantencion_hora', models.TextField(blank=True, null=True)),
                ('mantencion_tecnico_nombre', models.TextField(blank=True, null=True)),
                ('mantencion_tecnico_rut', models.TextField(blank=True, null=True)),
                ('mantencion_tecnico_telefono', models.TextField(blank=True, null=True)),
                ('mantencion_tecnico_email', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.ForeignKey(db_column='activo_id', on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='condominio_gestion.activo')),
                ('mantencion_estado', models.ForeignKey(blank=True, db_column='mantencion_estado_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones', to='condominio_gestion.mantencionestado')),
                ('mantencion_proveedor', models.ForeignKey(blank=True, db_column='mantencion_proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones', to='condominio_gestion.mantencionproveedor')),
            ],
            options={
                'verbose_name': 'Mantención',
                'verbose_name_plural': 'Mantenciones',
                'db_table': 'mantencion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MantencionProgramada',
            fields=[
                ('mantencion_programada_id', models.AutoField(primary_key=True, serialize=False)),
                ('mantencion_programada_fecha', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mantencion', models.OneToOneField(db_column='mantencion_id', on_delete=django.db.models.deletion.CASCADE, related_name='programada', to='condominio_gestion.mantencion')),
            ],
            options={
                'verbose_name': 'Mantención Programada',
                'verbose_name_plural': 'Mantenciones Programadas',
                'db_table': 'mantencion_programada',
                'ordering': ['mantencion_programada_fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['condominio'], name='idx_espacio_condominio'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['condominio'], name='idx_activo_condominio'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['espacio'], name='idx_activo_espacio'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['activo_tipo'], name='idx_activo_tipo'),
        ),
        migrations.AddIndex(
            model_name='mantencionprogramada',
            index=models.Index(fields=['mantencion'], name='idx_mt_programada_mantencion'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['activo'], name='idx_mantencion_activo'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['mantencion_proveedor'], name='idx_mantencion_proveedor'),
        ),
    ]
