# Generated by Django 6.0 on 2026-02-20 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('mantencion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mantencion_tipo', models.CharField(blank=True, choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva'), ('EMERGENCIA', 'Emergencia')], max_length=50, null=True)),
                ('mantencion_descripcion', models.TextField(blank=True, null=True)),
                ('mantencion_fecha_realizacion', models.DateField(blank=True, null=True)),
                ('mantencion_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mantencion_realizada_por', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Mantención',
                'verbose_name_plural': 'Mantenciones',
                'db_table': 'mantencion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MantencionEstado',
            fields=[
                ('mantencion_estado_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mantencion_estado_nombre', models.CharField(max_length=100)),
                ('mantencion_estado_descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Estado de Mantención',
                'verbose_name_plural': 'Estados de Mantención',
                'db_table': 'mantencion_estado',
                'ordering': ['mantencion_estado_nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantencionProgramada',
            fields=[
                ('mantencion_programada_id', models.AutoField(primary_key=True, serialize=False)),
                ('mantencion_programada_descripcion', models.TextField()),
                ('mantencion_programada_fecha', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Mantención Programada',
                'verbose_name_plural': 'Mantenciones Programadas',
                'db_table': 'mantencion_programada',
                'ordering': ['mantencion_programada_fecha'],
            },
        ),
        migrations.RemoveIndex(
            model_name='historialmantencion',
            name='idx_historial_activo',
        ),
        migrations.AddField(
            model_name='mantencion',
            name='activo',
            field=models.ForeignKey(db_column='activo_id', on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='condominio_gestion.activo'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='mantencion_estado',
            field=models.ForeignKey(blank=True, db_column='mantencion_estado_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones', to='condominio_gestion.mantencionestado'),
        ),
        migrations.AddField(
            model_name='mantencionprogramada',
            name='activo',
            field=models.ForeignKey(db_column='activo_id', on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones_programadas', to='condominio_gestion.activo'),
        ),
        migrations.AddField(
            model_name='mantencionprogramada',
            name='mantencion_estado',
            field=models.ForeignKey(blank=True, db_column='mantencion_estado_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones_programadas', to='condominio_gestion.mantencionestado'),
        ),
        migrations.RemoveField(
            model_name='historialmantencion',
            name='activo',
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['activo'], name='idx_mantencion_activo'),
        ),
        migrations.AddIndex(
            model_name='mantencionprogramada',
            index=models.Index(fields=['activo'], name='idx_mt_programada_activo'),
        ),
        migrations.DeleteModel(
            name='HistorialMantencion',
        ),
    ]
