# Generated by Django 6.0 on 2026-05-07 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio_gestion', '0002_mantencion_programada_descripcion'),
        ('copropietarios', '0002_persona_persona_acepta_notificacion_digital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoCobro',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_mes', models.IntegerField()),
                ('periodo_anio', models.IntegerField()),
                ('periodo_fecha_vencimiento', models.DateField()),
                ('periodo_cerrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='periodos_cobro', to='condominio_gestion.condominio')),
            ],
            options={
                'verbose_name': 'Período de Cobro',
                'verbose_name_plural': 'Períodos de Cobro',
                'db_table': 'periodo_cobro',
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='CuotaUnidad',
            fields=[
                ('cuota_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuota_monto_ordinario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cuota_monto_extraordinario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cuota_interes_mora', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cuota_saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cuota_pagada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='copropietarios.unidad')),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='finanzas.periodocobro')),
            ],
            options={
                'verbose_name': 'Cuota por Unidad',
                'verbose_name_plural': 'Cuotas por Unidad',
                'db_table': 'cuota_unidad',
                'ordering': ['periodo', 'unidad'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('presupuesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('presupuesto_anio', models.IntegerField()),
                ('presupuesto_monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('presupuesto_aprobado', models.BooleanField(default=False)),
                ('presupuesto_fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('presupuesto_activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='condominio_gestion.condominio')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuesto',
                'ordering': ['-presupuesto_anio'],
            },
        ),
        migrations.AddField(
            model_name='periodocobro',
            name='presupuesto',
            field=models.ForeignKey(blank=True, db_column='presupuesto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos', to='finanzas.presupuesto'),
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_concepto', models.CharField(max_length=200)),
                ('item_tipo', models.CharField(choices=[('ORDINARIO', 'Ordinario'), ('EXTRAORDINARIO', 'Extraordinario')], default='ORDINARIO', max_length=20)),
                ('item_monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item_descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('presupuesto', models.ForeignKey(db_column='presupuesto_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finanzas.presupuesto')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto',
                'verbose_name_plural': 'Ítems de Presupuesto',
                'db_table': 'item_presupuesto',
                'ordering': ['item_tipo', 'item_concepto'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMorosidad',
            fields=[
                ('morosidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('morosidad_meses', models.IntegerField(default=1)),
                ('morosidad_monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('morosidad_activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='morosidades', to='finanzas.periodocobro')),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='morosidades', to='copropietarios.unidad')),
            ],
            options={
                'verbose_name': 'Registro de Morosidad',
                'verbose_name_plural': 'Registros de Morosidad',
                'db_table': 'registro_morosidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorteSuministro',
            fields=[
                ('corte_id', models.AutoField(primary_key=True, serialize=False)),
                ('corte_fecha_habilitacion', models.DateField()),
                ('corte_acuerdo_asamblea', models.CharField(blank=True, max_length=300, null=True)),
                ('corte_meses_mora', models.IntegerField()),
                ('corte_ejecutado', models.BooleanField(default=False)),
                ('corte_fecha_reposicion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidad', models.ForeignKey(db_column='unidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='cortes_suministro', to='copropietarios.unidad')),
            ],
            options={
                'verbose_name': 'Corte de Suministro',
                'verbose_name_plural': 'Cortes de Suministro',
                'db_table': 'corte_suministro',
                'ordering': ['-corte_fecha_habilitacion'],
                'indexes': [models.Index(fields=['unidad'], name='idx_corte_unidad')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoFondo',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('movimiento_tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('movimiento_concepto', models.CharField(max_length=300)),
                ('movimiento_monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('movimiento_fecha', models.DateField()),
                ('movimiento_saldo_resultante', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominio', models.ForeignKey(db_column='condominio_id', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_fondo', to='condominio_gestion.condominio')),
                ('mantencion', models.ForeignKey(blank=True, db_column='mantencion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_fondo', to='condominio_gestion.mantencion')),
            ],
            options={
                'verbose_name': 'Movimiento de Fondo de Reserva',
                'verbose_name_plural': 'Movimientos de Fondo de Reserva',
                'db_table': 'movimiento_fondo',
                'ordering': ['-movimiento_fecha'],
                'indexes': [models.Index(fields=['condominio'], name='idx_movimiento_fondo_condominio')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('pago_fecha', models.DateField()),
                ('pago_monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago_medio', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20)),
                ('pago_referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('pago_registrado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuota', models.ForeignKey(db_column='cuota_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.cuotaunidad')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-pago_fecha'],
                'indexes': [models.Index(fields=['cuota'], name='idx_pago_cuota')],
            },
        ),
        migrations.AddIndex(
            model_name='cuotaunidad',
            index=models.Index(fields=['periodo'], name='idx_cuota_periodo'),
        ),
        migrations.AddIndex(
            model_name='cuotaunidad',
            index=models.Index(fields=['unidad'], name='idx_cuota_unidad'),
        ),
        migrations.AddConstraint(
            model_name='cuotaunidad',
            constraint=models.UniqueConstraint(fields=('periodo', 'unidad'), name='uq_cuota_periodo_unidad'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['condominio'], name='idx_presupuesto_condominio'),
        ),
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.UniqueConstraint(fields=('condominio', 'presupuesto_anio'), name='uq_presupuesto_condominio_anio'),
        ),
        migrations.AddIndex(
            model_name='periodocobro',
            index=models.Index(fields=['condominio'], name='idx_periodo_condominio'),
        ),
        migrations.AddConstraint(
            model_name='periodocobro',
            constraint=models.UniqueConstraint(fields=('condominio', 'periodo_mes', 'periodo_anio'), name='uq_periodo_condominio_mes_anio'),
        ),
        migrations.AddIndex(
            model_name='itempresupuesto',
            index=models.Index(fields=['presupuesto'], name='idx_item_presupuesto'),
        ),
        migrations.AddIndex(
            model_name='registromorosidad',
            index=models.Index(fields=['unidad'], name='idx_morosidad_unidad'),
        ),
        migrations.AddIndex(
            model_name='registromorosidad',
            index=models.Index(fields=['periodo'], name='idx_morosidad_periodo'),
        ),
    ]
