# Generated by Django 6.0 on 2026-05-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimientofondo',
            new_name='idx_mov_fondo_condominio',
            old_name='idx_movimiento_fondo_condominio',
        ),
    ]
